TESTS WITH ERRORS 
-------------------------------
TESTS FAILED  
test5 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "/Users/k2i/academics/automatedgradingapp/app/testing/kb-inference/gradingtests.py", line 151, in test5
    self.assertTrue(len(answer4) > 0)
AssertionError: False is not true

-------------------------------
TESTS SKIPPED 
-------------------------------
